name: Deploy project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/${{ secrets.PROJECT_FOLDER }}

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            composer install --no-dev --optimize-autoloader

            echo "Run migrations"
            php artisan migrate --force

            echo "Clear cache"
            php artisan optimize

            echo "Generating API documentation"
            php artisan l5-swagger:generate
